const { createClient } = require('@supabase/supabase-js');
const dotenv = require('dotenv');
dotenv.config();

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false }
});

const ADMIN_CHAT_ID = 1191760477;

const ENGLISH_CLINICAL_QUIZZES = [
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Isovolumetric Contraction Phase Dynamics`,
    question: 'Which of the following physiological events precisely marks the true onset of ventricular systole?',
    options: [
      'Mitral valve closure and the first heart sound (S1) with all valves closed and constant blood volume',
      'Aortic valve opening and the onset of rapid blood ejection into the systemic circulation',
      'Peak systolic pressure generation within the left ventricular cavity',
      'Atrial contraction delivering the final end-diastolic filling volume (atrial kick)'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> أي من الأحداث الفسيولوجية التالية يمثل البداية الحقيقية لانقباض البطين (Onset of Ventricular Systole) بدقة؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
انقباض البطين (Systole) يبدأ بالمللي ثانية لحظة انقباض جدار البطين وانغلاق الصمام الميترالي مسبباً الصوت الأول S1. في هذه المرحلة (Isovolumetric Contraction Phase) تكون كافة صمامات القلب مغلقة تماماً وحجم الدم ثابت ومش بيتحرك. خروج أول دفعة دم يحدث عند فتح الصمام الأورطي في مرحلة الـ Rapid Ejection (Mid-systole).

💡 <b>Exam Pearl:</b> Systole begins at S1 (Mitral closure) with isovolumetric contraction; blood ejection occurs later in mid-systole!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Mitral Valve Prolapse (MVP) - Auscultatory Timing Mechanism`,
    question: 'A 22-year-old woman is evaluated during a routine screening. Auscultation at the cardiac apex reveals a mid-systolic click followed by a late systolic murmur. Why does the click occur in mid-systole rather than at the onset of ventricular contraction?',
    options: [
      'Ejection of blood decreases left ventricular volume, slacking chordae tendineae and allowing abrupt leaflet prolapse into the left atrium',
      'The mitral valve remains completely open during the initial phase of ventricular systole',
      'Intraventricular pressure is inadequate to move valve leaflets during early systole',
      'The chordae tendineae contract actively only during the terminal phase of ventricular ejection'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> شابة 22 سنة، فحص قمة القلب أظهر Mid-systolic click يليه Late systolic murmur. لماذا تظهر الطقة في منتصف الانقباض وليس في بدايته؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
في بداية الانقباض (Early systole)، يكون البطين ممتلئاً بالدم (EDV)، مما يبقي الحبال الوترية (Chordae tendineae) مشدودة تمنع انقلاب الشرفة. مع قذف الدم في منتصف الانقباض، يصغر تجويف البطين فترتخي الحبال الوترية، مما يسمح لشرفة الصمام المترهلة بالانقلاب فجأة داخل الأذين مع صوت النقر الحاد (Click).

💡 <b>Exam Pearl:</b> In MVP: Early systole = full LV keeps chordae taut (silent). Mid-systole = smaller LV cavity slacks chordae -> sudden prolapse & Click!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Bicuspid Aortic Valve - Ejection Click Pathophysiology`,
    question: 'A 24-year-old male is referred for a murmur. Auscultation reveals a sharp, high-pitched ejection click heard shortly after S1 at the right upper sternal border, followed by a systolic murmur. What is the underlying mechanism of this early systolic sound?',
    options: [
      'Sudden abrupt doming and opening of a congenital stenotic, calcified bicuspid aortic valve as blood is forcefully ejected',
      'Prolapse of the posterior mitral leaflet into the left atrial chamber during mid-ejection',
      'Physiological turbulence generated by high-velocity laminar flow in an anatomically normal aorta',
      'Sudden closure of a mechanical prosthetic tilting-disc valve mechanism'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> شاب 24 سنة يعاني من لغط قلبي، وسُمعت نقرة حادة بعد S1 في أعلى يمين عظمة القص (Ejection click) يعقبها لغط انقباضي. ما ميكانيكية هذا الصوت؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
الصمام الأورطي الطبيعي ثلاثي الشرفات ناعم ويفتح بصمت تام. في حالة العيب الخلقي (Bicuspid Aortic Valve)، يكون الصمام ثنائي الشرفات ويتيبس مع السنين؛ وعندما ينقبض البطين يفتح الصمام فجأة بقوة وبرزعة حادة مع اندفاع الدم مسبباً الـ Aortic Ejection Click.

💡 <b>Exam Pearl:</b> Young adult + Aortic Stenosis + Ejection Click = Congenital Bicuspid Aortic Valve!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Cardiac Clicks Clinical Differentiation`,
    question: 'Which of the following clinical vignettes is accurately matched with its characteristic extra cardiac sound?',
    options: [
      'A 21-year-old asymptomatic female with an apical mid-to-late systolic click ➔ Mitral Valve Prolapse (MVP)',
      'A 65-year-old male with an aortic ejection click occurring during rapid ventricular filling in mid-diastole ➔ Aortic Stenosis',
      'A 50-year-old patient with an apical opening snap occurring immediately before the first heart sound (S1) ➔ Mitral Regurgitation',
      'A 30-year-old athlete with a sharp metallic closing click heard during isovolumetric contraction ➔ Bicuspid Aortic Valve'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> أي من الحالات السريرية التالية متطابقة بدقة مع صوت النقر المميز لها؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
• فتاة شابة مع Mid-systolic click عند القمة = MVP.
• الـ Ejection click تكون في بداية الانقباض مع فتح الصمام الأورطي Bicuspid.
• الـ Metallic closing click للصمام الصناعي المعدني عند انغلاقه.
• الـ Opening snap لضيق الميترالي بعد S2 في الانبساط.

💡 <b>Exam Pearl:</b> Young female + Mid-systolic click = MVP!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Mitral Regurgitation - Pan-systolic Murmur Dynamics`,
    question: 'A 58-year-old male presents with exertional fatigue. Auscultation reveals a high-pitched blowing pansystolic (holosystolic) murmur heard best at the apex radiating to the left axilla. Why does this murmur span the entire duration of ventricular systole from S1 to S2?',
    options: [
      'Left ventricular pressure exceeds left atrial pressure throughout the entire systolic cycle from isovolumetric contraction to aortic closure',
      'Aortic valve stenosis impedes continuous forward ejection across both systole and early diastole',
      'Mitral valve leaflets actively prolapse only during the terminal third of the ejection phase',
      'Diastolic pressure equilibration forces retrograde blood flow across the competent aortic orifice'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> رجل 58 سنة، لغط Pansystolic عند القمة ممتد للإبط. لماذا يستمر هذا اللغط طوال فترة الانقباض من S1 إلى S2؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
في ارتجاع الميترالي (MR)، الصمام يفشل في الإغلاق المحكم؛ وطوال فترة الانقباض (من لحظة S1 وقفل الصمامات وحتى S2 قفل الأورطي) يظل ضغط البطين أعلى بكثير من ضغط الأذين، مما يسبب تسريباً مستمراً للدم عبر الصمام طوال فترة الانقباض (Pansystolic).

💡 <b>Exam Pearl:</b> Pan-systolic = LV pressure > LA pressure from S1 to S2 continuously!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Aortic Stenosis - Ejection Systolic Crescendo-Decrescendo Murmur`,
    question: 'A 68-year-old male presents with exertional angina. Cardiac examination reveals a harsh crescendo-decrescendo mid-systolic ejection murmur best heard at the right 2nd intercostal space radiating to the carotids. What explains the mid-systolic crescendo-decrescendo configuration of this murmur?',
    options: [
      'Murmur intensity parallels transvalvular ejection velocity, peaking in mid-systole with maximal flow and diminishing as flow wanes before S2',
      'Regurgitant flow begins abruptly at S1 and remains uniform until the end of ventricular contraction',
      'Rapid left ventricular filling in early diastole causes transient turbulence across the calcified aortic root',
      'Atrial systolic contraction forces retrograde turbulent flow through the stenosed aortic orifice'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> رجل 68 سنة مع ذبحة وإغماء مجهودي، وسُمع لغط Crescendo-decrescendo mid-systolic عند الفضاء الضلعي الثاني الأيمن. ما تفسير هذا الشكل الصوتي؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
في ضيق الأورطي (AS)، يبدأ اللغط بعد فتح الصمام في منتصف الانقباض؛ ومع تسارع تدفق الدم يشتد الصوت (Crescendo) ليصل لذروته مع أقصى سرعة قذف، ثم يخفت (Decrescendo) مع تراجع كمية الدم قبل S2.

💡 <b>Exam Pearl:</b> AS murmur shape (Diamond-shaped / Crescendo-decrescendo) matches ejection flow velocity in mid-systole!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Aortic Regurgitation - Early Diastolic Auscultatory Timing`,
    question: 'A 45-year-old male is found to have a high-pitched, blowing early diastolic decrescendo murmur best heard along the left sternal border at end-expiration. What hemodynamic factor causes this murmur to peak immediately after S2?',
    options: [
      'The retrograde pressure gradient between the aorta (80-120 mmHg) and relaxing left ventricle (~0 mmHg) is maximal immediately following S2',
      'Left ventricular pressure rises above aortic pressure during the isovolumetric relaxation phase',
      'The stenotic mitral valve abruptly snaps open producing turbulent retrograde flow into the left atrium',
      'Atrial contraction produces a transient diastolic regurgitant jet across the mitral valve'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> مريض 45 سنة، سُمع لغط Early diastolic decrescendo على حافة القص اليسرى. ما السبب في أن اللغط يبلغ ذروته فوراً بعد S2؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
فور انغلاق الأورطي عند S2، ينخفض ضغط البطين إلى الصفر تقريباً بينما الأورطي ممتلئ بضغط مرتفع (80-120 mmHg). هذا الفارق الشديد في الضغط يسبب ارتداداً شلالياً فورياً للدم في بداية الانبساط، ويتلاشى تدريجياً (Decrescendo) مع تقارب الضغوط.

💡 <b>Exam Pearl:</b> AR murmur peaks right after S2 because the aorta-to-LV pressure gradient is at its absolute maximum!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Mitral Stenosis - Diastolic Sequence: Opening Snap and Rumble`,
    question: 'A 34-year-old female presents with dyspnea on exertion. Physical examination reveals an opening snap (OS) heard shortly after S2, followed by a low-pitched mid-diastolic rumbling murmur at the apex. What physiological mechanism accounts for the mid-diastolic rumbling murmur?',
    options: [
      'Passive rapid ventricular filling causing turbulent blood flow across the narrowed, stenotic mitral orifice during mid-diastole',
      'Retrograde leakage of blood from the left ventricle into the left atrium during isovolumetric relaxation',
      'High-velocity blood flow through a calcified aortic valve during the rapid ejection phase',
      'Vigorous atrial contraction during the final phase of diastole prior to S1'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> مريضة 34 سنة، سُمعت طقة انفتاح (OS) بعد S2 يعقبها لغط دحرجي خشن في منتصف الانبساط. ما الميكانيكية الفسيولوجية لهذا اللغط؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
بعد انغلاق الأورطي (S2) يفتح الميترالي بطقة حادة (OS)؛ وأثناء مرحلة الامتلاء السريع في منتصف الانبساط (Mid-diastole)، يعافر الدم ليمر عبر الصمام الميترالي الضيق، مما يحدث دوامات واضطراباً في تدفق الدم يسبب صوت الكركبة الدحرجية (Mid-diastolic rumbling murmur).

💡 <b>Exam Pearl:</b> Mid-diastolic rumble = blood struggling through the tight stenotic mitral orifice during passive rapid ventricular filling!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Mitral Stenosis - Presystolic Accentuation & Loss in Atrial Fibrillation`,
    question: 'A 40-year-old woman with known rheumatic mitral stenosis develops palpitations and worsening dyspnea. An ECG demonstrates atrial fibrillation (AF). On auscultation, which physical finding of mitral stenosis disappears following the onset of atrial fibrillation?',
    options: [
      'Presystolic accentuation of the diastolic murmur',
      'The opening snap (OS)',
      'The mid-diastolic rumbling murmur',
      'The accentuated, loud first heart sound (S1)'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> مريضة ضيق ميترالي أصيبت برجفان أذيني (AF). أي من العلامات السريرية لضيق الميترالي ستختفي تماماً بعد حدوث الـ AF؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
ظاهرة اشتداد اللغط قبل الانقباض (Presystolic accentuation) ناتجة عن انقباض الأذين النشط (Atrial kick) لدفع آخر دفعة دم عبر الصمام الضيق. في حالة الرجفان الأذيني (AF)، يرتجف الأذين بدون انقباض ميكانيكي حقيقي، فتضيع الـ Atrial kick ويختفي الـ Presystolic accentuation فوراً!

💡 <b>Exam Pearl:</b> Mitral Stenosis + Atrial Fibrillation (AF) ➔ Loss of Presystolic Accentuation!`
  },
  {
    course_code: 'CAD402',
    topic: `[UID:${ADMIN_CHAT_ID}] [USER_INPUT] Cardiac Murmurs Auscultatory Timing Master Matrix`,
    question: 'Which of the following pairings correctly aligns each primary valvular lesion with its diagnostic auscultatory timing and clinical descriptor?',
    options: [
      'Mitral Regurgitation: Holosystolic | Aortic Stenosis: Crescendo-decrescendo mid-systolic | Aortic Regurgitation: Early diastolic decrescendo | Mitral Stenosis: Mid-diastolic rumble with presystolic accentuation',
      'Mitral Regurgitation: Early diastolic decrescendo | Aortic Stenosis: Holosystolic | Aortic Regurgitation: Mid-systolic ejection | Mitral Stenosis: Late systolic crescendo',
      'Mitral Regurgitation: Mid-systolic ejection | Aortic Stenosis: Late diastolic | Aortic Regurgitation: Holosystolic | Mitral Stenosis: Early diastolic decrescendo',
      'Mitral Regurgitation: Late diastolic rumble | Aortic Stenosis: Early diastolic | Aortic Regurgitation: Holosystolic | Mitral Stenosis: Mid-systolic ejection'
    ],
    correct_option_index: 0,
    explanation: `📝 <b>ترجمة السؤال:</b> أي من التوافقات التالية يربط بدقة كل اعتلال صمامي بتوقيته ووصفه الصوتي؟

🔍 <b>الشرح العلمي وتريكة الراوند:</b>
1. Mitral Regurgitation (MR): Holosystolic (Pansystolic)
2. Aortic Stenosis (AS): Crescendo-decrescendo mid-systolic
3. Aortic Regurgitation (AR): Early diastolic decrescendo
4. Mitral Stenosis (MS): Mid-diastolic rumble with presystolic accentuation

💡 <b>Exam Pearl:</b> The classic auscultation quartet: MR (Pansystolic) | AS (Mid-systolic) | AR (Early diastolic) | MS (Mid-diastolic & Presystolic).`
  }
];

async function replaceQuizzes() {
  console.log('🔄 Cleaning old Arabic quizzes for user', ADMIN_CHAT_ID, '...');
  
  // 1. Delete all Arabic user-input quizzes for user 1191760477
  const { error: delErr } = await supabase
    .from('medical_spaced_quizzes')
    .delete()
    .ilike('topic', `%[UID:${ADMIN_CHAT_ID}]%[USER_INPUT]%`);
    
  if (delErr) {
    console.error('Delete error:', delErr.message);
  } else {
    console.log('✅ Cleaned old Arabic user quizzes successfully!');
  }

  // 2. Insert the 10 Medical English Quizzes
  console.log('🚀 Inserting 10 Medical English Quizzes into Spaced Repetition queue...');
  const now = new Date();

  for (let i = 0; i < ENGLISH_CLINICAL_QUIZZES.length; i++) {
    const q = ENGLISH_CLINICAL_QUIZZES[i];
    // Stagger next_review_at so they arrive gracefully throughout the day
    const staggerMinutes = i === 0 ? 0 : (i * 45);
    const nextReview = new Date(now.getTime() + staggerMinutes * 60 * 1000).toISOString();

    const metaObj = {
      options: q.options,
      correct_index: q.correct_option_index,
      explanation: q.explanation
    };
    const doctorPearlWithMeta = `<<<QUIZ_META_START>>>${JSON.stringify(metaObj)}<<<QUIZ_META_END>>> ${q.explanation}`.trim();

    const { data, error } = await supabase.from('medical_spaced_quizzes').insert({
      course_code: q.course_code,
      topic: q.topic,
      question: q.question,
      answer_and_explanation: q.explanation,
      doctor_pearl: doctorPearlWithMeta,
      repetition_level: 0,
      next_review_at: nextReview,
      is_mastered: false
    }).select('id');

    if (error) {
      console.error(`❌ Error inserting quiz ${i + 1}:`, error.message);
    } else {
      console.log(`✅ [${i + 1}/10] Inserted English Quiz: "${q.question.slice(0, 50)}..." (Review in ${staggerMinutes}m)`);
    }
  }

  // 3. Clear daily locks so the scheduler picks up the first English quiz immediately
  const { data: trackerRow } = await supabase
    .from('bot_sessions')
    .select('data')
    .eq('chat_id', 888888)
    .maybeSingle();

  if (trackerRow?.data) {
    const tracker = trackerRow.data;
    let modified = false;
    for (const k of Object.keys(tracker)) {
      if (k.startsWith('med_spaced_') || k.startsWith(`med_spaced_last_sent_${ADMIN_CHAT_ID}`)) {
        delete tracker[k];
        modified = true;
      }
    }
    if (modified) {
      await supabase
        .from('bot_sessions')
        .update({ data: tracker, updated_at: new Date().toISOString() })
        .eq('chat_id', 888888);
      console.log('✅ Cleared med_spaced cooldown locks for immediate dispatch!');
    }
  }

  console.log('🎉 Successfully converted all 10 cardiology quizzes to 100% Medical English!');
}

replaceQuizzes().catch(console.error);
